// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlc

import (
	"context"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_logs
`

func (q *Queries) CountAuditLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (event, actor_username, actor_ip, actor_user_agent, resource_registry, resource_package, resource_version, result, metadata_json, prev_hash, hash)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, timestamp, event, actor_username, actor_ip, actor_user_agent, resource_registry, resource_package, resource_version, result, metadata_json, prev_hash, hash
`

type CreateAuditLogParams struct {
	Event            string `json:"event"`
	ActorUsername    string `json:"actor_username"`
	ActorIp          string `json:"actor_ip"`
	ActorUserAgent   string `json:"actor_user_agent"`
	ResourceRegistry string `json:"resource_registry"`
	ResourcePackage  string `json:"resource_package"`
	ResourceVersion  string `json:"resource_version"`
	Result           string `json:"result"`
	MetadataJson     string `json:"metadata_json"`
	PrevHash         string `json:"prev_hash"`
	Hash             string `json:"hash"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, createAuditLog,
		arg.Event,
		arg.ActorUsername,
		arg.ActorIp,
		arg.ActorUserAgent,
		arg.ResourceRegistry,
		arg.ResourcePackage,
		arg.ResourceVersion,
		arg.Result,
		arg.MetadataJson,
		arg.PrevHash,
		arg.Hash,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.Event,
		&i.ActorUsername,
		&i.ActorIp,
		&i.ActorUserAgent,
		&i.ResourceRegistry,
		&i.ResourcePackage,
		&i.ResourceVersion,
		&i.Result,
		&i.MetadataJson,
		&i.PrevHash,
		&i.Hash,
	)
	return i, err
}

const getLatestAuditLog = `-- name: GetLatestAuditLog :one
SELECT id, timestamp, event, actor_username, actor_ip, actor_user_agent, resource_registry, resource_package, resource_version, result, metadata_json, prev_hash, hash FROM audit_logs ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetLatestAuditLog(ctx context.Context) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, getLatestAuditLog)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.Event,
		&i.ActorUsername,
		&i.ActorIp,
		&i.ActorUserAgent,
		&i.ResourceRegistry,
		&i.ResourcePackage,
		&i.ResourceVersion,
		&i.Result,
		&i.MetadataJson,
		&i.PrevHash,
		&i.Hash,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, timestamp, event, actor_username, actor_ip, actor_user_agent, resource_registry, resource_package, resource_version, result, metadata_json, prev_hash, hash FROM audit_logs ORDER BY timestamp DESC LIMIT ? OFFSET ?
`

type ListAuditLogsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Event,
			&i.ActorUsername,
			&i.ActorIp,
			&i.ActorUserAgent,
			&i.ResourceRegistry,
			&i.ResourcePackage,
			&i.ResourceVersion,
			&i.Result,
			&i.MetadataJson,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByActor = `-- name: ListAuditLogsByActor :many
SELECT id, timestamp, event, actor_username, actor_ip, actor_user_agent, resource_registry, resource_package, resource_version, result, metadata_json, prev_hash, hash FROM audit_logs WHERE actor_username = ? ORDER BY timestamp DESC LIMIT ? OFFSET ?
`

type ListAuditLogsByActorParams struct {
	ActorUsername string `json:"actor_username"`
	Limit         int64  `json:"limit"`
	Offset        int64  `json:"offset"`
}

func (q *Queries) ListAuditLogsByActor(ctx context.Context, arg ListAuditLogsByActorParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByActor, arg.ActorUsername, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Event,
			&i.ActorUsername,
			&i.ActorIp,
			&i.ActorUserAgent,
			&i.ResourceRegistry,
			&i.ResourcePackage,
			&i.ResourceVersion,
			&i.Result,
			&i.MetadataJson,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByEvent = `-- name: ListAuditLogsByEvent :many
SELECT id, timestamp, event, actor_username, actor_ip, actor_user_agent, resource_registry, resource_package, resource_version, result, metadata_json, prev_hash, hash FROM audit_logs WHERE event = ? ORDER BY timestamp DESC LIMIT ? OFFSET ?
`

type ListAuditLogsByEventParams struct {
	Event  string `json:"event"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListAuditLogsByEvent(ctx context.Context, arg ListAuditLogsByEventParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByEvent, arg.Event, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Event,
			&i.ActorUsername,
			&i.ActorIp,
			&i.ActorUserAgent,
			&i.ResourceRegistry,
			&i.ResourcePackage,
			&i.ResourceVersion,
			&i.Result,
			&i.MetadataJson,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
