// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlc

import (
	"context"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_logs
`

func (q *Queries) CountAuditLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (event, actor_username, actor_ip, actor_user_agent, resource_registry, resource_package, resource_version, result, metadata_json, prev_hash, hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, timestamp, event, actor_username, actor_ip, actor_user_agent, resource_registry, resource_package, resource_version, result, metadata_json, prev_hash, hash
`

type CreateAuditLogParams struct {
	Event            string
	ActorUsername    string
	ActorIp          string
	ActorUserAgent   string
	ResourceRegistry string
	ResourcePackage  string
	ResourceVersion  string
	Result           string
	MetadataJson     string
	PrevHash         string
	Hash             string
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, createAuditLog,
		arg.Event,
		arg.ActorUsername,
		arg.ActorIp,
		arg.ActorUserAgent,
		arg.ResourceRegistry,
		arg.ResourcePackage,
		arg.ResourceVersion,
		arg.Result,
		arg.MetadataJson,
		arg.PrevHash,
		arg.Hash,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.Event,
		&i.ActorUsername,
		&i.ActorIp,
		&i.ActorUserAgent,
		&i.ResourceRegistry,
		&i.ResourcePackage,
		&i.ResourceVersion,
		&i.Result,
		&i.MetadataJson,
		&i.PrevHash,
		&i.Hash,
	)
	return i, err
}

const getLatestAuditLog = `-- name: GetLatestAuditLog :one
SELECT id, timestamp, event, actor_username, actor_ip, actor_user_agent, resource_registry, resource_package, resource_version, result, metadata_json, prev_hash, hash FROM audit_logs ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetLatestAuditLog(ctx context.Context) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, getLatestAuditLog)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.Event,
		&i.ActorUsername,
		&i.ActorIp,
		&i.ActorUserAgent,
		&i.ResourceRegistry,
		&i.ResourcePackage,
		&i.ResourceVersion,
		&i.Result,
		&i.MetadataJson,
		&i.PrevHash,
		&i.Hash,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, timestamp, event, actor_username, actor_ip, actor_user_agent, resource_registry, resource_package, resource_version, result, metadata_json, prev_hash, hash FROM audit_logs ORDER BY timestamp DESC LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Event,
			&i.ActorUsername,
			&i.ActorIp,
			&i.ActorUserAgent,
			&i.ResourceRegistry,
			&i.ResourcePackage,
			&i.ResourceVersion,
			&i.Result,
			&i.MetadataJson,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByActor = `-- name: ListAuditLogsByActor :many
SELECT id, timestamp, event, actor_username, actor_ip, actor_user_agent, resource_registry, resource_package, resource_version, result, metadata_json, prev_hash, hash FROM audit_logs WHERE actor_username = $1 ORDER BY timestamp DESC LIMIT $2 OFFSET $3
`

type ListAuditLogsByActorParams struct {
	ActorUsername string
	Limit         int64
	Offset        int64
}

func (q *Queries) ListAuditLogsByActor(ctx context.Context, arg ListAuditLogsByActorParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByActor, arg.ActorUsername, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Event,
			&i.ActorUsername,
			&i.ActorIp,
			&i.ActorUserAgent,
			&i.ResourceRegistry,
			&i.ResourcePackage,
			&i.ResourceVersion,
			&i.Result,
			&i.MetadataJson,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByEvent = `-- name: ListAuditLogsByEvent :many
SELECT id, timestamp, event, actor_username, actor_ip, actor_user_agent, resource_registry, resource_package, resource_version, result, metadata_json, prev_hash, hash FROM audit_logs WHERE event = $1 ORDER BY timestamp DESC LIMIT $2 OFFSET $3
`

type ListAuditLogsByEventParams struct {
	Event  string
	Limit  int64
	Offset int64
}

func (q *Queries) ListAuditLogsByEvent(ctx context.Context, arg ListAuditLogsByEventParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByEvent, arg.Event, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Event,
			&i.ActorUsername,
			&i.ActorIp,
			&i.ActorUserAgent,
			&i.ResourceRegistry,
			&i.ResourcePackage,
			&i.ResourceVersion,
			&i.Result,
			&i.MetadataJson,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
