// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dependencies.sql

package sqlc

import (
	"context"
)

const getPackageDependencies = `-- name: GetPackageDependencies :many
SELECT id, version_id, dep_name, dep_version_range, dep_optional, dep_dev
FROM package_dependencies
WHERE version_id = $1
`

func (q *Queries) GetPackageDependencies(ctx context.Context, versionID int64) ([]PackageDependency, error) {
	rows, err := q.db.QueryContext(ctx, getPackageDependencies, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PackageDependency
	for rows.Next() {
		var i PackageDependency
		if err := rows.Scan(
			&i.ID,
			&i.VersionID,
			&i.DepName,
			&i.DepVersionRange,
			&i.DepOptional,
			&i.DepDev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPackageDependency = `-- name: InsertPackageDependency :exec
INSERT INTO package_dependencies (version_id, dep_name, dep_version_range, dep_optional, dep_dev)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (version_id, dep_name) DO NOTHING
`

type InsertPackageDependencyParams struct {
	VersionID       int64
	DepName         string
	DepVersionRange string
	DepOptional     int64
	DepDev          int64
}

func (q *Queries) InsertPackageDependency(ctx context.Context, arg InsertPackageDependencyParams) error {
	_, err := q.db.ExecContext(ctx, insertPackageDependency,
		arg.VersionID,
		arg.DepName,
		arg.DepVersionRange,
		arg.DepOptional,
		arg.DepDev,
	)
	return err
}
