// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type ApiToken struct {
	ID          int64        `json:"id"`
	UserID      int64        `json:"user_id"`
	Name        string       `json:"name"`
	TokenHash   string       `json:"token_hash"`
	TokenPrefix string       `json:"token_prefix"`
	ExpiresAt   sql.NullTime `json:"expires_at"`
	LastUsedAt  sql.NullTime `json:"last_used_at"`
	CreatedAt   time.Time    `json:"created_at"`
}

type AuditLog struct {
	ID               int64     `json:"id"`
	Timestamp        time.Time `json:"timestamp"`
	Event            string    `json:"event"`
	ActorUsername    string    `json:"actor_username"`
	ActorIp          string    `json:"actor_ip"`
	ActorUserAgent   string    `json:"actor_user_agent"`
	ResourceRegistry string    `json:"resource_registry"`
	ResourcePackage  string    `json:"resource_package"`
	ResourceVersion  string    `json:"resource_version"`
	Result           string    `json:"result"`
	MetadataJson     string    `json:"metadata_json"`
	PrevHash         string    `json:"prev_hash"`
	Hash             string    `json:"hash"`
}

type Package struct {
	ID            int64     `json:"id"`
	RegistryType  string    `json:"registry_type"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	License       string    `json:"license"`
	Homepage      string    `json:"homepage"`
	Repository    string    `json:"repository"`
	Status        string    `json:"status"`
	RequestedBy   string    `json:"requested_by"`
	ApprovedBy    string    `json:"approved_by"`
	BlockedReason string    `json:"blocked_reason"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type PackageDependency struct {
	ID              int64  `json:"id"`
	VersionID       int64  `json:"version_id"`
	DepName         string `json:"dep_name"`
	DepVersionRange string `json:"dep_version_range"`
	DepOptional     int64  `json:"dep_optional"`
	DepDev          int64  `json:"dep_dev"`
}

type PackageVersion struct {
	ID             int64        `json:"id"`
	PackageID      int64        `json:"package_id"`
	Version        string       `json:"version"`
	Size           int64        `json:"size"`
	ChecksumSha256 string       `json:"checksum_sha256"`
	ChecksumSha1   string       `json:"checksum_sha1"`
	StoragePath    string       `json:"storage_path"`
	Deprecated     int64        `json:"deprecated"`
	Yanked         int64        `json:"yanked"`
	MetadataJson   string       `json:"metadata_json"`
	SyncedAt       sql.NullTime `json:"synced_at"`
	CreatedAt      time.Time    `json:"created_at"`
}

type Policy struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	PolicyType string    `json:"policy_type"`
	ConfigToml string    `json:"config_toml"`
	Enabled    int64     `json:"enabled"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Registry struct {
	ID               int64     `json:"id"`
	Ecosystem        string    `json:"ecosystem"`
	Mode             string    `json:"mode"`
	Upstream         string    `json:"upstream"`
	AutoSync         int64     `json:"auto_sync"`
	AutoSyncInterval string    `json:"auto_sync_interval"`
	MaxVersions      int64     `json:"max_versions"`
	Enabled          int64     `json:"enabled"`
	ConfigJson       string    `json:"config_json"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type SchemaMigration struct {
	Version   int64     `json:"version"`
	AppliedAt time.Time `json:"applied_at"`
}

type SyncJob struct {
	ID             int64        `json:"id"`
	RegistryType   string       `json:"registry_type"`
	PackageName    string       `json:"package_name"`
	Status         string       `json:"status"`
	StartedAt      sql.NullTime `json:"started_at"`
	CompletedAt    sql.NullTime `json:"completed_at"`
	ErrorMessage   string       `json:"error_message"`
	PackagesSynced int64        `json:"packages_synced"`
	CreatedAt      time.Time    `json:"created_at"`
}

type User struct {
	ID           int64          `json:"id"`
	Username     string         `json:"username"`
	Email        sql.NullString `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Role         string         `json:"role"`
	Active       int64          `json:"active"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type UserRole struct {
	ID           int64     `json:"id"`
	UserID       int64     `json:"user_id"`
	Role         string    `json:"role"`
	RegistryType string    `json:"registry_type"`
	Namespace    string    `json:"namespace"`
	CreatedAt    time.Time `json:"created_at"`
}
