// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type ApiToken struct {
	ID          int64
	UserID      int64
	Name        string
	TokenHash   string
	TokenPrefix string
	ExpiresAt   sql.NullTime
	LastUsedAt  sql.NullTime
	CreatedAt   time.Time
}

type AuditLog struct {
	ID               int64
	Timestamp        time.Time
	Event            string
	ActorUsername    string
	ActorIp          string
	ActorUserAgent   string
	ResourceRegistry string
	ResourcePackage  string
	ResourceVersion  string
	Result           string
	MetadataJson     string
	PrevHash         string
	Hash             string
}

type Package struct {
	ID            int64
	RegistryType  string
	Name          string
	Description   string
	License       string
	Homepage      string
	Repository    string
	Status        string
	RequestedBy   string
	ApprovedBy    string
	BlockedReason string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type PackageDependency struct {
	ID              int64
	VersionID       int64
	DepName         string
	DepVersionRange string
	DepOptional     int64
	DepDev          int64
}

type PackageVersion struct {
	ID             int64
	PackageID      int64
	Version        string
	Size           int64
	ChecksumSha256 string
	ChecksumSha1   string
	StoragePath    string
	Deprecated     int64
	Yanked         int64
	MetadataJson   string
	SyncedAt       sql.NullTime
	CreatedAt      time.Time
}

type Policy struct {
	ID         int64
	Name       string
	PolicyType string
	ConfigToml string
	Enabled    int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Registry struct {
	ID               int64
	Ecosystem        string
	Mode             string
	Upstream         string
	AutoSync         int64
	AutoSyncInterval string
	MaxVersions      int64
	Enabled          int64
	ConfigJson       string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type SchemaMigration struct {
	Version   int32
	AppliedAt time.Time
}

type Setting struct {
	Key         string
	Value       string
	Category    string
	Description string
	UpdatedAt   time.Time
}

type SyncJob struct {
	ID             int64
	RegistryType   string
	PackageName    string
	Status         string
	StartedAt      sql.NullTime
	CompletedAt    sql.NullTime
	ErrorMessage   string
	PackagesSynced int64
	CreatedAt      time.Time
}

type User struct {
	ID           int64
	Username     string
	Email        sql.NullString
	PasswordHash string
	Role         string
	Active       int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UserRole struct {
	ID           int64
	UserID       int64
	Role         string
	RegistryType string
	Namespace    string
	CreatedAt    time.Time
}
