// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: packages.sql

package sqlc

import (
	"context"
)

const countAllPackages = `-- name: CountAllPackages :one
SELECT COUNT(*) FROM packages
`

func (q *Queries) CountAllPackages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllPackages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllPackagesByStatus = `-- name: CountAllPackagesByStatus :one
SELECT COUNT(*) FROM packages WHERE status = $1
`

func (q *Queries) CountAllPackagesByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllPackagesByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPackages = `-- name: CountPackages :one
SELECT COUNT(*) FROM packages WHERE registry_type = $1
`

func (q *Queries) CountPackages(ctx context.Context, registryType string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPackages, registryType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPackagesByStatus = `-- name: CountPackagesByStatus :one
SELECT COUNT(*) FROM packages WHERE registry_type = $1 AND status = $2
`

type CountPackagesByStatusParams struct {
	RegistryType string
	Status       string
}

func (q *Queries) CountPackagesByStatus(ctx context.Context, arg CountPackagesByStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPackagesByStatus, arg.RegistryType, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPackage = `-- name: CreatePackage :one
INSERT INTO packages (registry_type, name, description, license, homepage, repository, status, requested_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, registry_type, name, description, license, homepage, repository, status, requested_by, approved_by, blocked_reason, created_at, updated_at
`

type CreatePackageParams struct {
	RegistryType string
	Name         string
	Description  string
	License      string
	Homepage     string
	Repository   string
	Status       string
	RequestedBy  string
}

func (q *Queries) CreatePackage(ctx context.Context, arg CreatePackageParams) (Package, error) {
	row := q.db.QueryRowContext(ctx, createPackage,
		arg.RegistryType,
		arg.Name,
		arg.Description,
		arg.License,
		arg.Homepage,
		arg.Repository,
		arg.Status,
		arg.RequestedBy,
	)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.RegistryType,
		&i.Name,
		&i.Description,
		&i.License,
		&i.Homepage,
		&i.Repository,
		&i.Status,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.BlockedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePackage = `-- name: DeletePackage :exec
DELETE FROM packages WHERE id = $1
`

func (q *Queries) DeletePackage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePackage, id)
	return err
}

const getPackage = `-- name: GetPackage :one
SELECT id, registry_type, name, description, license, homepage, repository, status, requested_by, approved_by, blocked_reason, created_at, updated_at FROM packages WHERE registry_type = $1 AND name = $2 LIMIT 1
`

type GetPackageParams struct {
	RegistryType string
	Name         string
}

func (q *Queries) GetPackage(ctx context.Context, arg GetPackageParams) (Package, error) {
	row := q.db.QueryRowContext(ctx, getPackage, arg.RegistryType, arg.Name)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.RegistryType,
		&i.Name,
		&i.Description,
		&i.License,
		&i.Homepage,
		&i.Repository,
		&i.Status,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.BlockedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPackageByID = `-- name: GetPackageByID :one
SELECT id, registry_type, name, description, license, homepage, repository, status, requested_by, approved_by, blocked_reason, created_at, updated_at FROM packages WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPackageByID(ctx context.Context, id int64) (Package, error) {
	row := q.db.QueryRowContext(ctx, getPackageByID, id)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.RegistryType,
		&i.Name,
		&i.Description,
		&i.License,
		&i.Homepage,
		&i.Repository,
		&i.Status,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.BlockedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPackages = `-- name: ListPackages :many
SELECT id, registry_type, name, description, license, homepage, repository, status, requested_by, approved_by, blocked_reason, created_at, updated_at FROM packages WHERE registry_type = $1 ORDER BY name LIMIT $2 OFFSET $3
`

type ListPackagesParams struct {
	RegistryType string
	Limit        int64
	Offset       int64
}

func (q *Queries) ListPackages(ctx context.Context, arg ListPackagesParams) ([]Package, error) {
	rows, err := q.db.QueryContext(ctx, listPackages, arg.RegistryType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Package
	for rows.Next() {
		var i Package
		if err := rows.Scan(
			&i.ID,
			&i.RegistryType,
			&i.Name,
			&i.Description,
			&i.License,
			&i.Homepage,
			&i.Repository,
			&i.Status,
			&i.RequestedBy,
			&i.ApprovedBy,
			&i.BlockedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackagesByStatus = `-- name: ListPackagesByStatus :many
SELECT id, registry_type, name, description, license, homepage, repository, status, requested_by, approved_by, blocked_reason, created_at, updated_at FROM packages WHERE registry_type = $1 AND status = $2 ORDER BY name LIMIT $3 OFFSET $4
`

type ListPackagesByStatusParams struct {
	RegistryType string
	Status       string
	Limit        int64
	Offset       int64
}

func (q *Queries) ListPackagesByStatus(ctx context.Context, arg ListPackagesByStatusParams) ([]Package, error) {
	rows, err := q.db.QueryContext(ctx, listPackagesByStatus,
		arg.RegistryType,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Package
	for rows.Next() {
		var i Package
		if err := rows.Scan(
			&i.ID,
			&i.RegistryType,
			&i.Name,
			&i.Description,
			&i.License,
			&i.Homepage,
			&i.Repository,
			&i.Status,
			&i.RequestedBy,
			&i.ApprovedBy,
			&i.BlockedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPackages = `-- name: SearchPackages :many
SELECT id, registry_type, name, description, license, homepage, repository, status, requested_by, approved_by, blocked_reason, created_at, updated_at FROM packages WHERE registry_type = $1 AND name LIKE $2 ORDER BY name LIMIT $3 OFFSET $4
`

type SearchPackagesParams struct {
	RegistryType string
	Name         string
	Limit        int64
	Offset       int64
}

func (q *Queries) SearchPackages(ctx context.Context, arg SearchPackagesParams) ([]Package, error) {
	rows, err := q.db.QueryContext(ctx, searchPackages,
		arg.RegistryType,
		arg.Name,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Package
	for rows.Next() {
		var i Package
		if err := rows.Scan(
			&i.ID,
			&i.RegistryType,
			&i.Name,
			&i.Description,
			&i.License,
			&i.Homepage,
			&i.Repository,
			&i.Status,
			&i.RequestedBy,
			&i.ApprovedBy,
			&i.BlockedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePackageStatus = `-- name: UpdatePackageStatus :exec
UPDATE packages SET status = $1, approved_by = $2, blocked_reason = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $4
`

type UpdatePackageStatusParams struct {
	Status        string
	ApprovedBy    string
	BlockedReason string
	ID            int64
}

func (q *Queries) UpdatePackageStatus(ctx context.Context, arg UpdatePackageStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePackageStatus,
		arg.Status,
		arg.ApprovedBy,
		arg.BlockedReason,
		arg.ID,
	)
	return err
}

const upsertPackage = `-- name: UpsertPackage :one
INSERT INTO packages (registry_type, name, status, requested_by)
VALUES ($1, $2, 'pending', $3)
ON CONFLICT (registry_type, name) DO UPDATE SET updated_at = CURRENT_TIMESTAMP
RETURNING id, registry_type, name, description, license, homepage, repository, status, requested_by, approved_by, blocked_reason, created_at, updated_at
`

type UpsertPackageParams struct {
	RegistryType string
	Name         string
	RequestedBy  string
}

func (q *Queries) UpsertPackage(ctx context.Context, arg UpsertPackageParams) (Package, error) {
	row := q.db.QueryRowContext(ctx, upsertPackage, arg.RegistryType, arg.Name, arg.RequestedBy)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.RegistryType,
		&i.Name,
		&i.Description,
		&i.License,
		&i.Homepage,
		&i.Repository,
		&i.Status,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.BlockedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
