// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: policies.sql

package sqlc

import (
	"context"
)

const getPolicy = `-- name: GetPolicy :one
SELECT id, name, policy_type, config_toml, enabled, created_at, updated_at
FROM policies WHERE name = $1 LIMIT 1
`

func (q *Queries) GetPolicy(ctx context.Context, name string) (Policy, error) {
	row := q.db.QueryRowContext(ctx, getPolicy, name)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PolicyType,
		&i.ConfigToml,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPolicies = `-- name: ListPolicies :many
SELECT id, name, policy_type, config_toml, enabled, created_at, updated_at
FROM policies ORDER BY name
`

func (q *Queries) ListPolicies(ctx context.Context) ([]Policy, error) {
	rows, err := q.db.QueryContext(ctx, listPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PolicyType,
			&i.ConfigToml,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePolicyEnabled = `-- name: UpdatePolicyEnabled :exec
UPDATE policies SET enabled = $1, updated_at = CURRENT_TIMESTAMP
WHERE name = $2
`

type UpdatePolicyEnabledParams struct {
	Enabled int64
	Name    string
}

func (q *Queries) UpdatePolicyEnabled(ctx context.Context, arg UpdatePolicyEnabledParams) error {
	_, err := q.db.ExecContext(ctx, updatePolicyEnabled, arg.Enabled, arg.Name)
	return err
}

const upsertPolicy = `-- name: UpsertPolicy :exec
INSERT INTO policies (name, policy_type, config_toml, enabled)
VALUES ($1, $2, $3, $4)
ON CONFLICT (name) DO UPDATE SET
    config_toml = $3,
    enabled = $4,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertPolicyParams struct {
	Name       string
	PolicyType string
	ConfigToml string
	Enabled    int64
}

func (q *Queries) UpsertPolicy(ctx context.Context, arg UpsertPolicyParams) error {
	_, err := q.db.ExecContext(ctx, upsertPolicy,
		arg.Name,
		arg.PolicyType,
		arg.ConfigToml,
		arg.Enabled,
	)
	return err
}
