// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registries.sql

package sqlc

import (
	"context"
)

const getRegistry = `-- name: GetRegistry :one
SELECT id, ecosystem, mode, upstream, auto_sync, auto_sync_interval, max_versions, enabled, config_json, created_at, updated_at
FROM registries WHERE ecosystem = $1 LIMIT 1
`

func (q *Queries) GetRegistry(ctx context.Context, ecosystem string) (Registry, error) {
	row := q.db.QueryRowContext(ctx, getRegistry, ecosystem)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Ecosystem,
		&i.Mode,
		&i.Upstream,
		&i.AutoSync,
		&i.AutoSyncInterval,
		&i.MaxVersions,
		&i.Enabled,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRegistries = `-- name: ListRegistries :many
SELECT id, ecosystem, mode, upstream, auto_sync, auto_sync_interval, max_versions, enabled, config_json, created_at, updated_at
FROM registries ORDER BY ecosystem
`

func (q *Queries) ListRegistries(ctx context.Context) ([]Registry, error) {
	rows, err := q.db.QueryContext(ctx, listRegistries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Registry
	for rows.Next() {
		var i Registry
		if err := rows.Scan(
			&i.ID,
			&i.Ecosystem,
			&i.Mode,
			&i.Upstream,
			&i.AutoSync,
			&i.AutoSyncInterval,
			&i.MaxVersions,
			&i.Enabled,
			&i.ConfigJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRegistryEnabled = `-- name: UpdateRegistryEnabled :exec
UPDATE registries SET enabled = $1, updated_at = CURRENT_TIMESTAMP
WHERE ecosystem = $2
`

type UpdateRegistryEnabledParams struct {
	Enabled   int64
	Ecosystem string
}

func (q *Queries) UpdateRegistryEnabled(ctx context.Context, arg UpdateRegistryEnabledParams) error {
	_, err := q.db.ExecContext(ctx, updateRegistryEnabled, arg.Enabled, arg.Ecosystem)
	return err
}

const upsertRegistry = `-- name: UpsertRegistry :exec
INSERT INTO registries (ecosystem, mode, upstream, auto_sync, auto_sync_interval, max_versions, enabled, config_json)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (ecosystem) DO UPDATE SET
    mode = $2,
    upstream = $3,
    auto_sync = $4,
    auto_sync_interval = $5,
    max_versions = $6,
    enabled = $7,
    config_json = $8,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertRegistryParams struct {
	Ecosystem        string
	Mode             string
	Upstream         string
	AutoSync         int64
	AutoSyncInterval string
	MaxVersions      int64
	Enabled          int64
	ConfigJson       string
}

func (q *Queries) UpsertRegistry(ctx context.Context, arg UpsertRegistryParams) error {
	_, err := q.db.ExecContext(ctx, upsertRegistry,
		arg.Ecosystem,
		arg.Mode,
		arg.Upstream,
		arg.AutoSync,
		arg.AutoSyncInterval,
		arg.MaxVersions,
		arg.Enabled,
		arg.ConfigJson,
	)
	return err
}
