// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sqlc

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT key, value, category, description, updated_at
FROM settings WHERE key = $1 LIMIT 1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Category,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}

const getSettingsByCategory = `-- name: GetSettingsByCategory :many
SELECT key, value, category, description, updated_at
FROM settings WHERE category = $1 ORDER BY key
`

func (q *Queries) GetSettingsByCategory(ctx context.Context, category string) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, getSettingsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Category,
			&i.Description,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettings = `-- name: ListSettings :many
SELECT key, value, category, description, updated_at
FROM settings ORDER BY category, key
`

func (q *Queries) ListSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Category,
			&i.Description,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSettingValue = `-- name: UpdateSettingValue :exec
UPDATE settings SET value = $1, updated_at = CURRENT_TIMESTAMP
WHERE key = $2
`

type UpdateSettingValueParams struct {
	Value string
	Key   string
}

func (q *Queries) UpdateSettingValue(ctx context.Context, arg UpdateSettingValueParams) error {
	_, err := q.db.ExecContext(ctx, updateSettingValue, arg.Value, arg.Key)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (key, value, category, description, updated_at)
VALUES ($1, $2, $3, $4, CURRENT_TIMESTAMP)
ON CONFLICT (key) DO UPDATE SET value = $2, updated_at = CURRENT_TIMESTAMP
`

type UpsertSettingParams struct {
	Key         string
	Value       string
	Category    string
	Description string
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting,
		arg.Key,
		arg.Value,
		arg.Category,
		arg.Description,
	)
	return err
}
