// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync_jobs.sql

package sqlc

import (
	"context"
)

const createSyncJob = `-- name: CreateSyncJob :one
INSERT INTO sync_jobs (registry_type, package_name, status)
VALUES ($1, $2, 'pending')
RETURNING id, registry_type, package_name, status, started_at, completed_at, error_message, packages_synced, created_at
`

type CreateSyncJobParams struct {
	RegistryType string
	PackageName  string
}

func (q *Queries) CreateSyncJob(ctx context.Context, arg CreateSyncJobParams) (SyncJob, error) {
	row := q.db.QueryRowContext(ctx, createSyncJob, arg.RegistryType, arg.PackageName)
	var i SyncJob
	err := row.Scan(
		&i.ID,
		&i.RegistryType,
		&i.PackageName,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.PackagesSynced,
		&i.CreatedAt,
	)
	return i, err
}

const getSyncJob = `-- name: GetSyncJob :one
SELECT id, registry_type, package_name, status, started_at, completed_at, error_message, packages_synced, created_at
FROM sync_jobs WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSyncJob(ctx context.Context, id int64) (SyncJob, error) {
	row := q.db.QueryRowContext(ctx, getSyncJob, id)
	var i SyncJob
	err := row.Scan(
		&i.ID,
		&i.RegistryType,
		&i.PackageName,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.PackagesSynced,
		&i.CreatedAt,
	)
	return i, err
}

const listSyncJobs = `-- name: ListSyncJobs :many
SELECT id, registry_type, package_name, status, started_at, completed_at, error_message, packages_synced, created_at
FROM sync_jobs ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListSyncJobsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListSyncJobs(ctx context.Context, arg ListSyncJobsParams) ([]SyncJob, error) {
	rows, err := q.db.QueryContext(ctx, listSyncJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncJob
	for rows.Next() {
		var i SyncJob
		if err := rows.Scan(
			&i.ID,
			&i.RegistryType,
			&i.PackageName,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.PackagesSynced,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStaleSyncJobsFailed = `-- name: MarkStaleSyncJobsFailed :exec
UPDATE sync_jobs SET status = 'failed', error_message = 'interrupted by server restart'
WHERE status = 'running'
`

func (q *Queries) MarkStaleSyncJobsFailed(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markStaleSyncJobsFailed)
	return err
}

const updateSyncJobStatus = `-- name: UpdateSyncJobStatus :exec
UPDATE sync_jobs
SET status          = $1,
    packages_synced = $2,
    error_message   = $3,
    started_at      = CASE WHEN $1 = 'running' AND started_at IS NULL
                           THEN CURRENT_TIMESTAMP ELSE started_at END,
    completed_at    = CASE WHEN $1 IN ('done', 'failed')
                           THEN CURRENT_TIMESTAMP ELSE completed_at END
WHERE id = $4
`

type UpdateSyncJobStatusParams struct {
	Status         string
	PackagesSynced int64
	ErrorMessage   string
	ID             int64
}

func (q *Queries) UpdateSyncJobStatus(ctx context.Context, arg UpdateSyncJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSyncJobStatus,
		arg.Status,
		arg.PackagesSynced,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}
