// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (user_id, name, token_hash, token_prefix, expires_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, name, token_hash, token_prefix, expires_at, last_used_at, created_at
`

type CreateAPITokenParams struct {
	UserID      int64        `json:"user_id"`
	Name        string       `json:"name"`
	TokenHash   string       `json:"token_hash"`
	TokenPrefix string       `json:"token_prefix"`
	ExpiresAt   sql.NullTime `json:"expires_at"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUserRole = `-- name: CreateUserRole :one
INSERT INTO user_roles (user_id, role, registry_type, namespace)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, role, registry_type, namespace, created_at
`

type CreateUserRoleParams struct {
	UserID       int64  `json:"user_id"`
	Role         string `json:"role"`
	RegistryType string `json:"registry_type"`
	Namespace    string `json:"namespace"`
}

func (q *Queries) CreateUserRole(ctx context.Context, arg CreateUserRoleParams) (UserRole, error) {
	row := q.db.QueryRowContext(ctx, createUserRole,
		arg.UserID,
		arg.Role,
		arg.RegistryType,
		arg.Namespace,
	)
	var i UserRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.RegistryType,
		&i.Namespace,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :exec
DELETE FROM api_tokens WHERE id = ?
`

func (q *Queries) DeleteAPIToken(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAPIToken, id)
	return err
}

const deleteUserRole = `-- name: DeleteUserRole :exec
DELETE FROM user_roles WHERE id = ?
`

func (q *Queries) DeleteUserRole(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserRole, id)
	return err
}

const getAPIToken = `-- name: GetAPIToken :one
SELECT id, user_id, name, token_hash, token_prefix, expires_at, last_used_at, created_at FROM api_tokens WHERE token_hash = ? LIMIT 1
`

func (q *Queries) GetAPIToken(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getAPIToken, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT id, user_id, role, registry_type, namespace, created_at FROM user_roles WHERE user_id = ? AND role = ? AND registry_type = ? AND namespace = ? LIMIT 1
`

type GetUserRoleParams struct {
	UserID       int64  `json:"user_id"`
	Role         string `json:"role"`
	RegistryType string `json:"registry_type"`
	Namespace    string `json:"namespace"`
}

func (q *Queries) GetUserRole(ctx context.Context, arg GetUserRoleParams) (UserRole, error) {
	row := q.db.QueryRowContext(ctx, getUserRole,
		arg.UserID,
		arg.Role,
		arg.RegistryType,
		arg.Namespace,
	)
	var i UserRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.RegistryType,
		&i.Namespace,
		&i.CreatedAt,
	)
	return i, err
}

const listAPITokensByUser = `-- name: ListAPITokensByUser :many
SELECT id, user_id, name, token_hash, token_prefix, expires_at, last_used_at, created_at FROM api_tokens WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListAPITokensByUser(ctx context.Context, userID int64) ([]ApiToken, error) {
	rows, err := q.db.QueryContext(ctx, listAPITokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT id, user_id, role, registry_type, namespace, created_at FROM user_roles WHERE user_id = ?
`

func (q *Queries) ListUserRoles(ctx context.Context, userID int64) ([]UserRole, error) {
	rows, err := q.db.QueryContext(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRole{}
	for rows.Next() {
		var i UserRole
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.RegistryType,
			&i.Namespace,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPITokenLastUsed = `-- name: UpdateAPITokenLastUsed :exec
UPDATE api_tokens SET last_used_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) UpdateAPITokenLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateAPITokenLastUsed, id)
	return err
}
