// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: versions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countPackageVersions = `-- name: CountPackageVersions :one
SELECT COUNT(*) FROM package_versions WHERE package_id = $1
`

func (q *Queries) CountPackageVersions(ctx context.Context, packageID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPackageVersions, packageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPackageVersion = `-- name: CreatePackageVersion :one
INSERT INTO package_versions (package_id, version, size, checksum_sha256, checksum_sha1, storage_path, metadata_json, synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, package_id, version, size, checksum_sha256, checksum_sha1, storage_path, deprecated, yanked, metadata_json, synced_at, created_at
`

type CreatePackageVersionParams struct {
	PackageID      int64
	Version        string
	Size           int64
	ChecksumSha256 string
	ChecksumSha1   string
	StoragePath    string
	MetadataJson   string
	SyncedAt       sql.NullTime
}

func (q *Queries) CreatePackageVersion(ctx context.Context, arg CreatePackageVersionParams) (PackageVersion, error) {
	row := q.db.QueryRowContext(ctx, createPackageVersion,
		arg.PackageID,
		arg.Version,
		arg.Size,
		arg.ChecksumSha256,
		arg.ChecksumSha1,
		arg.StoragePath,
		arg.MetadataJson,
		arg.SyncedAt,
	)
	var i PackageVersion
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Version,
		&i.Size,
		&i.ChecksumSha256,
		&i.ChecksumSha1,
		&i.StoragePath,
		&i.Deprecated,
		&i.Yanked,
		&i.MetadataJson,
		&i.SyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deletePackageVersion = `-- name: DeletePackageVersion :exec
DELETE FROM package_versions WHERE id = $1
`

func (q *Queries) DeletePackageVersion(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePackageVersion, id)
	return err
}

const getPackageVersion = `-- name: GetPackageVersion :one
SELECT id, package_id, version, size, checksum_sha256, checksum_sha1, storage_path, deprecated, yanked, metadata_json, synced_at, created_at FROM package_versions WHERE package_id = $1 AND version = $2 LIMIT 1
`

type GetPackageVersionParams struct {
	PackageID int64
	Version   string
}

func (q *Queries) GetPackageVersion(ctx context.Context, arg GetPackageVersionParams) (PackageVersion, error) {
	row := q.db.QueryRowContext(ctx, getPackageVersion, arg.PackageID, arg.Version)
	var i PackageVersion
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Version,
		&i.Size,
		&i.ChecksumSha256,
		&i.ChecksumSha1,
		&i.StoragePath,
		&i.Deprecated,
		&i.Yanked,
		&i.MetadataJson,
		&i.SyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPackageVersions = `-- name: ListPackageVersions :many
SELECT id, package_id, version, size, checksum_sha256, checksum_sha1, storage_path, deprecated, yanked, metadata_json, synced_at, created_at FROM package_versions WHERE package_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListPackageVersionsParams struct {
	PackageID int64
	Limit     int64
	Offset    int64
}

func (q *Queries) ListPackageVersions(ctx context.Context, arg ListPackageVersionsParams) ([]PackageVersion, error) {
	rows, err := q.db.QueryContext(ctx, listPackageVersions, arg.PackageID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PackageVersion
	for rows.Next() {
		var i PackageVersion
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.Version,
			&i.Size,
			&i.ChecksumSha256,
			&i.ChecksumSha1,
			&i.StoragePath,
			&i.Deprecated,
			&i.Yanked,
			&i.MetadataJson,
			&i.SyncedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
